import {useEffect,useMemo,useState} from 'react';
import {auditedLedger} from './auditedLedger.js';
import {money,pct,rangeFor,ymd} from './forensicModel.js';

// Shared presentation primitives are kept separate from all ledger calculations.
import {css,logo,Line,Metric,Table} from './dashboardPresentation.jsx';
export default function AuditedDashboard(){
 const today=ymd(new Date());
 const [api,setApi]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(true),[active,setActive]=useState('Sales'),[line,setLine]=useState('Overall'),[mode,setMode]=useState('Month'),[start,setStart]=useState(today.slice(0,7)+'-01'),[end,setEnd]=useState(today),[clock,setClock]=useState(Date.now());
 async function refresh(){setBusy(true);setError('');try{const r=await fetch('/api/dashboard',{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Source unavailable');setApi(j);}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{refresh();const t=setInterval(()=>refresh(),120000),c=setInterval(()=>setClock(Date.now()),30000);return()=>{clearInterval(t);clearInterval(c)}},[]);
 const range=rangeFor(mode,start,end),invalid=!range.start||!range.end||range.start>range.end;
 const m=useMemo(()=>auditedLedger(api,range.start,range.end,line),[api,range.start,range.end,line]);
 const stale=api&&clock-new Date(api.fetchedAt).getTime()>300000;
 const trust=error?'SOURCE ERROR':!api?'LOADING':stale?'STALE':invalid?'INVALID PERIOD':m.trust;
 const available=api&&!invalid&&!error&&!stale&&m.critical===0;
 const display=n=>available?money(n):'—';
 const tone=trust==='RECONCILED'?'good':trust==='REVIEW'?'warn':'bad';
 const rows=m.jobs.filter(j=>j.approved||j.billed||j.cost||j.vendorOrders.length);
 const stageRows=Object.entries(m.current.reduce((a,j)=>(a[j.stage]=(a[j.stage]||0)+1,a),{}));
 const cards={Sales:{value:display(m.sales),lines:[['Approved orders',available?m.formalCount:'—'],['Additional scope lines',available?m.salesEntries.filter(s=>s.kind==='Additional scope').length:'—'],['Basis','Approval / ratification date']]},Ops:{value:available?`${m.current.length} open jobs`:'—',lines:[...stageRows,['Basis','Current source state']]},People:{value:available?`${m.vendors.filter(v=>v.openJobs>0).length} vendors on open jobs`:'—',lines:[['Remaining work orders',display(m.vendors.reduce((n,v)=>n+v.remainingCost,0))],['Future cost budget',display(m.futureCost)],['Capacity','Planning estimate']]},Finance:{value:display(m.billed),lines:[['Open projected job profit',display(m.projectedProfit)],['Closed recorded job profit',display(m.closedProfit)],['Total receivable',display(m.ar)]]}};
 const jobName=s=>`${s.job?.number||''} · ${s.job?.name||'Unassigned'}`;
 return <><style>{css}</style><div className='app'>
  <div className='head'><div className='brand'><img className='logo' src={logo} alt='TenanTurn'/><div><h1>TenanTurn</h1><div className='muted'>Audited JobTread Dashboard · v2026.09.30</div></div></div><div><div className='metriclabel'>Source and rule status</div><div className={`metricvalue ${tone}`}>{trust}</div><div className='small muted'>{api?m.critical:'—'} critical · {api?m.review:'—'} review</div></div></div>
  <div className='biznav'>{[['Overall','Overall'],['MR','Make Ready'],['CS','Contractor Services']].map(([k,v])=><button key={k} className={line===k?'on':''} onClick={()=>setLine(k)}>{v}</button>)}</div>
  <div className='toolbar'>{['Week','Month','Quarter','Custom'].map(k=><button key={k} className={mode===k?'on':''} onClick={()=>setMode(k)}>{k}</button>)}{mode==='Custom'&&<><label>From <input type='date' value={start} onChange={e=>setStart(e.target.value)}/></label><label>To <input type='date' value={end} onChange={e=>setEnd(e.target.value)}/></label></>}<button disabled={busy} onClick={refresh}>{busy?'Refreshing…':'Refresh now'}</button><span className='period'>{range.start} → {range.end} · America/Chicago</span></div>
  <div className='small muted'>Live JobTread · automatic refresh every 2 minutes · last successful refresh {api?new Date(api.fetchedAt).toLocaleString('en-US',{timeZone:'America/Chicago'}):'—'}</div>
  {api&&m.critical>0&&<div className='notice bad'>Financial figures are withheld because source or reconciliation checks failed. See the exception ledger below.</div>}{error&&<div className='notice bad'>Refresh failed: {error}. Financial figures are withheld until the source refresh succeeds.</div>}{stale&&<div className='notice bad'>Source is older than 5 minutes. Financial figures are withheld until a fresh source passes the checks.</div>}{invalid&&<div className='notice bad'>Start date must be on or before end date.</div>}
  {available&&<div className={`notice ${tone}`}>{m.trust==='RECONCILED'?'Loaded records passed the implemented source and reconciliation checks.':'Source records have unresolved review items. Read the evidence below before relying on affected figures.'} JobTread records are checked; independent bank reconciliation and company overhead are outside this feed.</div>}
  <div className='ownergrid'>{Object.entries(cards).map(([name,c])=><button key={name} onClick={()=>setActive(name)} className={`owner ${active===name?'active':''}`}><h2>{name} <span>›</span></h2><div className='hero'>{c.value}</div>{c.lines.map(([a,b])=><Line key={a} a={a} b={b}/>)}</button>)}</div>
  {available&&<section className='detail'><h2>{active}</h2>
   {active==='Sales'&&<><div className='grid'><Metric label='Net production sales' value={display(m.sales)} note='Every approved order plus separately evidenced additional scope; reimbursements excluded.'/><Metric label='Gross new sales / increases' value={display(m.grossSales)}/><Metric label='Credits / price reductions' value={display(m.salesAdjustments)}/><Metric label='Formal orders' value={m.formalCount}/><Metric label='Additional scope lines' value={m.salesEntries.filter(s=>s.kind==='Additional scope').length}/><Metric label='Issued billing is separate' value={display(m.billed)}/></div><h3>Every included sales entry</h3><Table headers={['Job','Document / Scope','Date','Evidence basis','Production sales','Source ID']} rows={m.salesEntries.map(s=>[jobName(s),s.item?.name||s.doc.fullName,s.date,s.basis,money(s.value),s.id])}/><div className='foot'>Table sum equals the Sales card to the cent. Progress payments, remaining balances, old contracts, and at-cost reimbursements create no new sale. Customer-payment ratification has its own stated evidence basis. Net sales include evidenced price reductions and credits.</div></>}
   {active==='Ops'&&<><div className='foot'>Current open jobs are independent of the selected sales period. Invoice or vendor-payment activity alone never proves whole-job completion. Unclear stages stay visible.</div><Table headers={['Job','Stage','Customer','PM / source','Approved production','Issued production','Remaining cost budget','Reviews']} rows={m.current.map(j=>[jobName(j),j.stage,j.src.billingCustomer,`${j.src.pm} / ${j.src.workSource}`,money(j.approved),money(j.billed),money(j.remainingBudget),j.reviews])}/></>}
   {active==='People'&&<><h3>Current vendor commitments and capacity estimates</h3><Table headers={['Vendor','Open jobs','Remaining work orders','Estimated weeks','Capacity confidence','Checked attributed billing','Checked actual cost']} rows={m.vendors.map(v=>[v.name,v.openJobs,money(v.remainingCost),v.rolling8WeeklyCost>0?(v.remainingCost/v.rolling8WeeklyCost).toFixed(2):'Insufficient history',v.capacityConfidence,money(v.attributedRevenue),money(v.finalActualCost)])}/><div className='foot'>Work-order remainder is calculated per vendor and scope on open jobs. Capacity is an estimate from completed-work history, not a verified schedule. Unassigned work appears in future cost budget, not a fabricated vendor commitment.</div><h3>Client / PM sales in selected period</h3><Table headers={['PM / Client','Included scope entries','Approved production sales']} rows={m.pms.map(p=>[p.name,p.count,money(p.sales)])}/><div className='foot'>These rows use the same sales entries as the Sales card. Unresolved attribution stays Unattributed.</div></>}
   {active==='Finance'&&<><div className='grid'><Metric label='Issued production billing' value={display(m.billed)} note='Pending and approved invoices by issue date; draft and denied excluded.'/><Metric label='Open projected job profit' value={display(m.projectedProfit)} note='Approved scope less budgeted/recorded costs. Provisional; no draft revenue.'/><Metric label='Closed recorded job profit' value={display(m.closedProfit)} note='Lifetime closed-job ledger result; unresolved cost/reimbursement records may affect it.'/><Metric label='Checked closed-job subset' value={display(m.checkedProfit)} note={`${m.checkedJobs} of ${m.closedJobs} closed jobs passed the implemented checks.`}/></div><h3>Current balances and recorded payments</h3><Line a='Total customer receivable' b={display(m.ar)}/><Line a='Recorded vendor payable' b={display(m.ap)}/><Line a='Held customer credits' b={display(m.core.heldCustomerCredits)}/><Line a='Customer payments applied in period' b={display(m.customerPaymentsApplied)}/><Line a='Independent bank confirmation' b='Not connected'/><div className='foot'>Receivables include reimbursement balances. Job profit excludes at-cost pass-through revenue and corresponding costs; it includes recorded job costs and fees. It is not company net profit or available cash.</div><h3>Every job’s lifetime economics</h3><Table headers={['Job','Status','Approved production','Issued production','Actual job cost','Recorded job profit','Recorded margin','Projected cost','Projected profit','Reviews']} rows={rows.map(j=>[jobName(j),j.status,money(j.approved),money(j.billed),money(j.cost),money(j.profitRecorded),j.billed?pct(100*j.profitRecorded/j.billed):'—',money(j.projectedCost),j.job.closedOn?'—':money(j.projectedProfit),j.reviews])}/><h3>Period-issued invoice ledger</h3><Table headers={['Job','Invoice','Issue date','Status','Total with reimbursements','Current balance','Source ID']} rows={m.periodInvoices.map(d=>[jobName(d),d.fullName,d.issueDate,d.status,money(d.priceWithTax),money(d.balance),d.id])}/><h3>Outstanding customer invoices</h3><Table headers={['Job','Invoice','Total','Paid','Balance']} rows={m.arDocs.map(d=>[jobName(d),d.fullName,money(d.priceWithTax),money(d.amountPaid),money(d.balance)])}/><h3>Outstanding vendor bills</h3><Table headers={['Job','Bill','Vendor','Balance']} rows={m.apDocs.map(d=>[jobName(d),d.fullName,d.account?.name,money(d.balance)])}/></>}
  </section>}
  {api&&!invalid&&<section className='detail'><h2>Data integrity — every exception</h2><Table headers={['Severity','Job / Account','Rule','Source detail']} rows={m.exceptions.map(e=>[e.severity,e.job,e.code,e.detail])}/><div className='foot'>No truncation: {m.exceptions.length} exceptions displayed. Review items retain their severity and prevent a checked status.</div><h3>Source coverage</h3><Table headers={['Source','Loaded records']} rows={Object.entries(api.sourceCoverage?.counts||{}).map(([k,v])=>[k,v])}/><div className='foot'>All source pages must load and counts must match. Refreshes with changing source collections are rejected. Every card and detail row uses one shared ledger model. The dashboard never edits JobTread.</div></section>}
 </div></>;
}
